### ISSUE TITLE
pymesync errors get ignored, causing issues

### ISSUE THREAD

**Issue by subnomo** [osuosl/timesync-frontend-flask#107]
[`error_message`](https://github.com/osuosl/timesync-frontend-flask/blob/develop/app/util.py#L79) is called but often the True/False returned is totally ignored:

https://github.com/osuosl/timesync-frontend-flask/blob/develop/app/views/view_activities.py#L35
https://github.com/osuosl/timesync-frontend-flask/blob/develop/app/views/edit_user.py#L23
https://github.com/osuosl/timesync-frontend-flask/blob/develop/app/views/create_time.py#L25

The errors are flashed to the user, however if the method depends on the `array` value passed as a parameter, it will fail.

The methods should only proceed normally if `error_message` returns `False`.

**Comment by aaroncohen73** [comment]
I found the cause while investigating another issue. Since they're both simple fixes I'll put them together in a PR
