### ISSUE TITLE
Editing project members does nothing

### ISSUE THREAD

**Issue by Kennric** [osuosl/timesync-frontend-flask#115]
If I edit a project, select a new member in the multi-select box, and submit, I see a message saying project was successfully submitted, but the new member is not added to the project (does not appear in the project list in the app, nor are they added on the server).

If I click on edit project again, the new member is still selected in the multi-select. 

No errors appear at any time.

**Comment by aaroncohen73** [comment]
@Kennric I can't seem to replicate this bug

**Comment by subnomo** [comment]
I wasn't ever able to replicate this. Either a fluke or it was fixed, I guess.
