### ISSUE TITLE
Error when TIMESYNC_URL isn't a real TimeSync instance

### ISSUE THREAD

**Issue by pop** [osuosl/timesync-frontend-flask#121]
The application should do a small test to make sure the TIMESYNC_URL is a valid Timesync instance. Currently if it's set to something like `https://timesync.example.com` the tests (`nosetests`) silently fail. There should be some output to tell the person running the application that this is the case.

**Comment by subnomo** [comment]
I can't seem to reproduce this bug, for me the tests all pass (because requests are mocked).

**Comment by subnomo** [comment]
I seem to be able to reproduce this now, pending fix in #120.

**Comment by subnomo** [comment]
Closed by #120.
