### ISSUE TITLE
Use Redis as cache

### ISSUE THREAD

**Issue by subnomo** [osuosl/timesync-frontend-flask#19]
Things like token expiry and user permissions shouldn't all be stored in the session.

[redis-py](https://github.com/andymccurdy/redis-py) is a good Python module.

**Comment by aaroncohen73** [comment]
Since I've finished the report page a bit earlier than expected, I'd like to start working on this.

**Comment by Kennric** [comment]
I don't think this is a good idea, we don't really need to do this, and there are security issues with storing secrets in redis. Lets keep it in the session.

**Comment by matthewrsj** [comment]
Additionally, why is using redis better than storing in the session?

**Comment by pop** [comment]
Yeah can we get a more thorough report on why storing stuff like this in the session is bad practice? Last I checked 95% of webapps store secrets in sessions.

**Comment by subnomo** [comment]
@matthewrsj @ElijahCaine Perhaps I misremember, but I thought @Kennric suggested storing all these in the session would be "clunky".

**Comment by subnomo** [comment]
We won't be using redis, everything we need can be stored in session.
