### ISSUE TITLE
CSS Styling [8]

### ISSUE THREAD

**Issue by subnomo** [osuosl/timesync-frontend-flask#33]
The site needs some CSS styling to look pretty. It'd also be good to minify our assets.

A good solution for both would be to use [Flask-Assets](https://flask-assets.readthedocs.io/en/latest/) to manage our assets.

**Comment by pop** [comment]
+1 to this. A nice coat of [bootstrap](https://getbootstrap.com) would really make a world of difference. Don't get me wrong, I appreciate our [homage to the best website ever](http://motherfuckingwebsite.com/), this is going to be used by people that want a bit more than what we currently have.
