### ISSUE TITLE
Standardize naming convention

### ISSUE THREAD

**Issue by aaroncohen73** [osuosl/timesync-frontend-flask#42]
@subnomo uses the mixed case naming convention for variables and functions (i.e. isLoggedIn) while I prefer to use lowercase with underscores (i.e. is_logged_in). We should decide on one or the other so our code doesn't look sloppy and hacked-together.

I'm in favor of using lowercase with underscores because I think that it looks cleaner and is easier to read.

**Comment by subnomo** [comment]
I do prefer camelCase but I'm pretty sure snake_case is the correct way to do things according to PEP8. We should use your way instead.

**Comment by matthewrsj** [comment]
Yes, please change everything to snake case when you have time. Snake case follows naming conventions outlined in PEP8 and _I believe_ it makes code more readable.

**Comment by pop** [comment]
@aaroncohen73 @subnomo do you think this can be closed now?

**Comment by aaroncohen73** [comment]
Closed via #47
