### ISSUE TITLE
Dealing with lots of time entries on /times

### ISSUE THREAD

**Issue by aaroncohen73** [osuosl/timesync-frontend-flask#62]
Currently, because the TimeSync server has lots of time entries, the `/times` endpoint takes a long time to load and is pretty large. What, if anything, can we do to deal with a large quantity of time entries?

**Comment by pop** [comment]
@aaroncohen73 Can you be more specific about the problem? How long does it take to load, what kind of wait does the user have to go through, etc?

**Comment by aaroncohen73** [comment]
@ElijahCaine Currently, the page takes about 8 seconds to load and is about 1 MB of pure text. Since the `/times` endpoint is where the user goes to edit/delete times and both of those pages redirect the user back to `/times`after the user has edited/deleted a time (Another 8 second wait), there's a lot of time in a regular workflow where the user is just waiting for the page to load.

My suspicion is that the template engine is what's taking the longest, but I haven't done any testing to verify that.

**Comment by pop** [comment]
@aaroncohen73 I would investigate to see if the template engine is in fact what's taking the longest amount of time.
If there aren't any optimizations we can make while still dumping all of the data on /times/ then I would make the /times/ page just a form to search for a smaller subset of the data; while still allowing users to request all data it would allow for the _option_ to get exactly what they want a bit quicker.
Thoughts @Kennric ?

**Comment by aaroncohen73** [comment]
@ElijahCaine Looks like I was wrong. Actually getting the data from TimeSync seems to be taking the longest by far. Making `/times` just a form to search for times wouldn't be a very difficult tweak though.
