### ISSUE TITLE
Better pymesync error handling

### ISSUE THREAD

**Issue by subnomo** [osuosl/timesync-frontend-flask#7]
[TODO here.](https://github.com/osuosl/timesync-frontend-flask/blob/ae2688bc23c8cd3f256666ba1cc38d84b15c91ed/app/views.py#L35)

Instead of just responding with, "There was an error," we should tell the user what the problem was and return them to the login page so they can try again.

**Comment by matthewrsj** [comment]
You can do this by simply printing `token["error"]` or `token["pymesync error"]`
