### ISSUE TITLE
Deal with authentication timeouts properly

### ISSUE THREAD

**Issue by MaraJade** [osuosl/timesync-frontend-flask#80]
Currently, when the token expires, you merely get an error. It would be nice if it redirected the user to the login page when the token expires. If possible, it should redirect back to where the user was with any form data they were working with still there.

Token expiration also has a tendency of breaking redirects, as the login check for the views sees a token but doesn't check if it's still valid, and so breaks the view by trying to do things while unauthenticated.

**Comment by subnomo** [comment]
Small correction: you shouldn't get an error when the token expires. If the token is expired, `is_logged_in` will fail and will log the user out, redirecting them to the index page.

https://github.com/osuosl/timesync-frontend-flask/blob/1ad5e59cfc4013b9eaa9fe97bc19d2d13ee36405/app/util.py#L72-L74

**Comment by subnomo** [comment]
If anyone can replicate this, let me know. This seems to be implemented already.

[Example](https://github.com/osuosl/timesync-frontend-flask/blob/578b1706cc9b0076ff0a100dcabc4965d40af7e9/app/views/view_times.py#L10-L11)

**Comment by aaroncohen73** [comment]
I think the issue here is that is_logged_in just naively checks the token expiration time and not if the token is actually valid.

**Comment by aaroncohen73** [comment]
The issue with tokens becoming invalid and causing weird things to happen when `is_logged_in` produces a false positive has been shown to be an issue with PM2 running on the timesync-node server. Closing the issue.
